# C1 — Prise en main d'OpenSSL. Le serveur est correctement chiffré ; il n'y a
# PAS d'attaque réseau ici. L'objectif est d'apprendre à récupérer et vérifier
# un certificat X.509. Le flag est embarqué dans le certificat lui-même (OU).
events {}
http {
  server {
    listen 8451 ssl;
    server_name bank.tp.lan;

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
      proxy_pass http://portal:5000;
      proxy_set_header Host $host;
    }
  }
}
