[prof_vm]
prof_host ansible_host=127.0.0.1 ansible_port=2222 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[teacher]
# IP du prof si besoin

[students]
poste01 ansible_host=192.168.50.11
poste02 ansible_host=192.168.50.12
poste03 ansible_host=192.168.50.13