# ==============================================================================
# 1. ENVIRONNEMENTS VIRTUELS (VM Prof via QEMU / Packer)
# ==============================================================================
[vm_prof]
prof_host_vm ansible_host=127.0.0.1 ansible_port=2222 ansible_user=ansible

# ==============================================================================
# 2. MACHINES PHYSIQUES (Salle de TP)
# ==============================================================================
[teacher_physical]
pc-prof ansible_host=192.168.1.100 ansible_user=admin

[students_physical]
pc-etu01 ansible_host=192.168.1.101 ansible_user=tp
pc-etu02 ansible_host=192.168.1.102 ansible_user=tp
pc-etu03 ansible_host=192.168.1.103 ansible_user=tp

# ==============================================================================
# 3. GROUPES LOGIQUES MAÎTRES (Utilisés par les Playbooks)
# ==============================================================================
# Actif par défaut : la VM QEMU
[teacher:children]
vm_prof

# Pour basculer sur le serveur physique de la salle de TP,
# commente 'vm_prof' ci-dessus et décommente 'teacher_physical' ci-dessous :
#[teacher:children]
#teacher_physical

# Regroupement complet du parc physique pour l'administration globale
[classroom_hosts:children]
teacher_physical
students_physical

# ==============================================================================
# 4. VARIABLES GLOBALES ET PAR GROUPE
# ==============================================================================
[vm_prof:vars]
is_virtual=true
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[classroom_hosts:vars]
is_virtual=false