# ==============================================================================
# 1. ENVIRONNEMENTS VIRTUELS (QEMU / Packer - Local)
# ==============================================================================
[vm_prof]
prof_host_vm ansible_host=127.0.0.1 ansible_port=2222 ansible_user=ansible

[vm_prof:vars]
is_virtual=true
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# ==============================================================================
# 4. GROUPES LOGIQUES MAÎTRES
# ==============================================================================

# SCÉNARIO A : VM Locale (QEMU) - Actif pour Packer
[teacher:children]
vm_prof

# Groupe d'alias si vos playbooks ciblent direct 'prof_host'
[prof_host:children]
vm_prof